aliases: []
creation_timestamp: 1738443182175
current_stage: None
description: null
last_updated_timestamp: 1738443182175
name: training_model_1
run_id: 4d67a39dddb94981a6dfe782c0375642
run_link: null
source: file:///D:/git/adult_wages/model_db/mlflow.db/0/4d67a39dddb94981a6dfe782c0375642/artifacts/models/training_model_1
status: READY
status_message: null
storage_location: file:///D:/git/adult_wages/model_db/mlflow.db/0/4d67a39dddb94981a6dfe782c0375642/artifacts/models/training_model_1
user_id: null
version: 1
