aliases: []
creation_timestamp: 1738464534771
current_stage: None
description: null
last_updated_timestamp: 1738464534771
name: training_model_2
run_id: 06588ced73d84d6cba771179f1682682
run_link: null
source: file:///D:/git/adult_wages/model_db/mlflow.db/0/06588ced73d84d6cba771179f1682682/artifacts/models/training_model_2
status: READY
status_message: null
storage_location: file:///D:/git/adult_wages/model_db/mlflow.db/0/06588ced73d84d6cba771179f1682682/artifacts/models/training_model_2
user_id: null
version: 2
