artifact_uri: file:///D:/git/adult_wages/model_db/mlflow.db/0/4d67a39dddb94981a6dfe782c0375642/artifacts
end_time: 1738443182276
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4d67a39dddb94981a6dfe782c0375642
run_name: training_pipeline
run_uuid: 4d67a39dddb94981a6dfe782c0375642
source_name: ''
source_type: 4
source_version: ''
start_time: 1738443146465
status: 3
tags: []
user_id: abhij
