name: Run Pytest

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn==1.5.2
          pip install -r requirements.txt
      
      - name: Set up MLFLOW tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/abbeymaj/my-first-repo.mlflow" >> $GITHUB_ENV
      
      - name: Run Pytest
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_API_TOKEN: ${{ secrets.DAGSHUB_API_TOKEN }}
        run: pytest -W ignore src/unit_tests/