name: Run Pytest

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: sqlite:///${{ github.workspace }}/model_db/mlflow.db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn==1.5.2
          pip install -r requirements.txt
      
      - name: Make the bash script executable
        run: chmod +x ./src/unit_tests/start_mlflow_server.sh
      
      - name: List directory contents
        run: ls -R src/unit_tests
      
      - name: Start MLflow server 
        run: ./src/unit_tests/start_mlflow_server.sh

      - name: Set MLFlow tracking uri 
        run: | 
          export MLFLOW_TRACKING_URI="sqlite:///${{ github.workspace }}/model_db/mlflow.db"
      
      - name: Run Pytest
        run: pytest -W ignore src/unit_tests/